/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_ua_taras_appc_MainActivity
#define _Included_ua_taras_appc_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_taras_appc_MainActivity
 * Method:    configure
 */

JNIEXPORT jobject JNICALL Java_ua_taras_appc_MainActivity_configure
(JNIEnv *env, jclass thiz);

JNIEXPORT void JNICALL Java_ua_taras_appc_MainActivity_readuart
  (JNIEnv *env, jobject thiz);

JNIEXPORT void JNICALL Java_ua_taras_appc_MainActivity_close
  (JNIEnv *env, jobject thiz);

JNIEXPORT void JNICALL Java_helperClasses_RfidListenerManager_set_1interruption_1status
(JNIEnv *env, jobject thiz, jint status);

#ifdef __cplusplus
}
#endif
#endif
